name: Tests

on:
  push:
    branches:
      - develop

env:
  server-directory: ./server
  client-directory: ./client

jobs:
  rails-test:
    strategy:
      matrix:
        ruby: ['3.2.1']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
        working-directory: ${{ env.server-directory }}
      - name: Setup database
        run: |
          rails db:create
          rails db:migrate RAILS_ENV=test
        working-directory: ${{ env.server-directory }}
      - name: Run tests
        run: rails test
        working-directory: ${{ env.server-directory }}
  nextjs-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16', '18']
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: yarn install
      working-directory: ${{ env.client-directory }}
    - name: Run tests
      run: yarn test
      working-directory: ${{ env.client-directory }}
